const actionTypes = {
  SET_RATES_PAGE_CURRENCY: 'SET_RATES_PAGE_CURRENCY',
  SET_RATES_PAGE_DATE: 'SET_RATES_PAGE_DATE',
  SET_GLOBAL_CURRENCIES: 'SET_GLOBAL_CURRENCIES',
  SET_FILTER_OPEN_FILTER: 'SET_FILTER_OPEN_FILTER',
  SET_FILTER_BASE_CURRENCY: 'SET_FILTER_BASE_CURRENCY',
  SET_FILTER_TARGET_CURRENCY: 'SET_FILTER_TARGET_CURRENCY',
  SET_FILTER_EXCHANGE_DATE: 'SET_FILTER_EXCHANGE_DATE',
  SET_FILTER_EXCHANGE_AMOUNT: 'SET_FILTER_EXCHANGE_AMOUNT',
  SET_ERROR: 'SET_ERROR',
  RESET_FILTERS: 'RESET_FILTERS',
};

export default actionTypes;
